import type { Metadata } from "next";
import '../styles/reset.scss'
import '../styles/globals.scss'
import '../styles/fonts.scss'
import { Header } from "@/components/layout/header/header";

import { Montserrat } from 'next/font/google';
import { Footer } from "@/components/layout/footer/footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
